### ISSUE TITLE
execution error: Error: TypeError: undefined is not an object (evaluating 'binURL.path') (-2700) fix

### ISSUE THREAD

**Issue by jrizz922** [alfredapp/wheres-the-binary-workflow#1]
### Feature details

Hi @vitorgalvao ,

 I was getting an execution error: Error: TypeError: undefined is not an object (evaluating 'binURL.path') when running this, so I made a quick fix that worked for me. Wanted to post in case it helps someone else.

`binURL` is `undefined` at the point where we're trying to access its `path` property. This occurs because the `dirContents` function can return an empty array, and when you attempt to access properties of elements in this array without checking if they exist, you encounter this error. To fix this issue, I added a check to ensure `binURL` is not `undefined` before attempting to access its properties. This modification ensures that we gracefully handle cases where `dirContents` returns an empty array, preventing attempts to access properties of `undefined`. 

```
// Main
const sfItems = envVar("PATH")
  .split(":")
  .flatMap(pathDir => dirContents(pathDir))
  .flatMap(binURL => {
	if (!binURL) return []; // Check if binURL is undefined and return an empty array if so

	const binPath = binURL.path.js;

	if (!isExecutable(binPath)) return [];

	const binFinal = binURL.URLByResolvingSymlinksInPath.path.js;
	const isSymlink = binPath !== binFinal;
	const subtitleText = isSymlink ? `${binPath} → ${binFinal}` : binPath;
	const optMod = isSymlink ?
	  { subtitle: binFinal, arg: binFinal } :
	  { subtitle: "Not a symlink", valid: false};

	return {
	  title: $(binPath).lastPathComponent.js,
	  subtitle: subtitleText,
	  arg: binPath,
	  mods: { alt: optMod }
	};
  });

JSON.stringify({
  cache: { seconds: 3600, loosereload: true },
  items: sfItems
});
```

Thanks

**Comment by vitorgalvao** [comment]
> This occurs because the `dirContents` function can return an empty array, and when you attempt to access properties of elements in this array without checking if they exist, you encounter this error.

Not quite. Empty arrays are discarded by `flatMap`, that is an explicit feature. Plus, an empty array wouldn’t pose an issue because there would be nothing to iterate over. The problem stems instead from non-existing directories returning `undefined`. A better fix is to solve it at the source with a `|| []`. An update will be live later today. Thank you for reporting.
