### ISSUE TITLE
tiny typo

### ISSUE THREAD

**Issue by luckman212** [alfredapp/wheres-the-binary-workflow#2]
### Feature details

hi @vitorgalvao 

Thanks for this useful workflow.

I found a tiny typo here... 🙂 (Searck → Search)

https://github.com/alfredapp/wheres-the-binary-workflow/blob/0cd1a5fee10dac7c8bf300d73efb1b34cae5bb52/Workflow/info.plist#L202

**Comment by vitorgalvao** [comment]
Thank you. Fixed.
